package org.vetcabinet.exception.controller;

import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.vetcabinet.exception.AlreadyExistsException;
import org.vetcabinet.exception.AuthorizationException;
import org.vetcabinet.exception.NotFoundException;
import org.vetcabinet.exception.model.ErrorResponse;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import static org.springframework.http.HttpStatus.*;

@RestControllerAdvice
public class ErrorHandler {
    private static final DateTimeFormatter PATTERN = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss:SSS");

    @ExceptionHandler
    @ResponseStatus(NOT_FOUND)
    public ErrorResponse handleNotFoundException(final NotFoundException exception) {
        return new ErrorResponse(exception.getMessage(),
                LocalDateTime.now().format(PATTERN),
                "Запрашиваемые данные не были найдены");
    }

    @ExceptionHandler
    @ResponseStatus(CONFLICT)
    public ErrorResponse handleAlreadyExistsException(final AlreadyExistsException exception) {
        return new ErrorResponse(exception.getMessage(),
                LocalDateTime.now().format(PATTERN),
                "Данные уже есть в системе");
    }

    @ExceptionHandler
    @ResponseStatus(UNAUTHORIZED)
    public ErrorResponse handleAuthorizationException(final AuthorizationException exception) {
        return new ErrorResponse(exception.getMessage(),
                LocalDateTime.now().format(PATTERN),
                "Ошибка авторизации");
    }
}
